//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label cal;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.TextBox txtValue1;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.TextBox txtValue2;
		
		protected System.Web.UI.WebControls.Button btnAdd;
		
		protected System.Web.UI.WebControls.Button btnSub;
		
		protected System.Web.UI.WebControls.Button btnMult;
		
		protected System.Web.UI.WebControls.Button btnDiv;
		
		protected System.Web.UI.WebControls.Label lblAns;
	}
}
